/*
"try" --> Se a promessa for aceita(resolve) ele tenta executar 
o c√≥digo, se consegue faz o que t√° dentro das chaves;

"Catch" --> Se a promessa for rejeitada, ou se 
der erro no try, faz oq t√° entre as chaves.
*/

//Fun√ß√£o de promessa, que executa uma promessa a cada 1seg:
const myPromise = () =>
  new Promise((resolve, reject) => {
    return setTimeout(() => {
      //TODO: Colocar tipo um if de resolve e reject
      reject("Promessa REJEITADA! (reject) ü•∫üòï");
    }, 1000);
  });

//-------------------Como fazer Try e Catch numa promessa com Async e Await:
const exec = async () => {
  try {
    await myPromise();
    console.log("Promessa REALIZADA! (resolve) ü§©üòé");
  } catch (error) {
    console.warn(error);
  }
};

//Executa a fun√ß√£o para criar uma promessa:
exec();

/*
---------------------Try e Catch numa promessa sem Async/Await:

myPromise()
  .then(() => {
    console.log("Primeira promessa executada");
  })
  .catch((error) => {
    console.warn(error);
  });

  //Executa a fun√ß√£o para criar uma promessa:
myPromise();
*/
